openapi: 3.1.0

info:
  title: Journal API
  description: API for journal management
  version: 1.0.0

servers:
  - url: https://api.example.com

paths:
  $ref: './paths/journals.yaml'

components:
  securitySchemes:
    $ref: './components/security.yaml'
  schemas:
    CreateOpeningAssetBalanceJournalRequest:
      $ref: './schemas/journals.yaml#/CreateOpeningAssetBalanceJournalRequest'
    CreateOpeningAssetBalanceJournalResponse:
      $ref: './schemas/journals.yaml#/CreateOpeningAssetBalanceJournalResponse'
    ErrorResponse:
      $ref: './schemas/error.yaml#/ErrorResponse'

